### ISSUE TITLE
Fresh install spikes CPU to 100%

### ISSUE THREAD

**Issue by lklepner** [modit/socket.io-adapter-mongo#11]
Hi,

I've noticed fresh installs of the adapter are pegging the CPU on my Node 4.4.1 Mongo 3.x environments with Node CPU usage at 65% and Mongo at 35%. 

I've put together a very simple Express / Socket.io / Socket.io-adapter-mongo example which demonstrates this - 
https://github.com/lklepner/socket.io-adapter-mongo-bug-test

I've been digging into the dependancies trying to determine the cause but haven't figured it out yet. 

In older builds of my project, which haven't had a fresh npm install recently, I am not experiencing the CPU problem. Perhaps one of the dependancies is out of whack?

Lou

**Comment by lklepner** [comment]
Doing more testing I've found that the problem does not exist with older versions of the mongodb module. 

I'm not sure exactly when the problem began but I've found that the mongo module v2.1.4 does not have the problem whereas v2.1.16 does.

**Comment by lklepner** [comment]
Looking over the history from mongodb-core 1.3.1 to 1.3.4 -
https://github.com/christkv/mongodb-core/blob/V1.3.4/HISTORY.md

This stood out as a potential cause of the problem --> "Fixed issue where tailable cursor would not retry even though cursor was still alive."

**Comment by lklepner** [comment]
Looks like mubsub might be the underlying issue -
https://github.com/scttnlsn/mubsub/issues/49

**Comment by CrackerakiUA** [comment]
I have same issue. Temporary fix is to use 2.1.7 version?

**Comment by lklepner** [comment]
Thats correct

**Comment by CrackerakiUA** [comment]
"debug": "2.2.0",
    "mongodb-uri": "^0.9.7",
    "msgpack-js": "0.3.0",
    "mubsub": "^1.1.2",
    "socket.io-adapter": "0.4.0",
    "uid2": "0.0.3"
those packages we are using, debug must be 2.1.7?

**Comment by CrackerakiUA** [comment]
If you could do a pr with temp fix, that would be amazing.

**Comment by lklepner** [comment]
On my end I resolved the issue by requiring "mongodb": "2.1.7" in my main package file. You want need to delete your node_modules directory and do a fresh npm install to get things straightened out.

**Comment by lklepner** [comment]
mubsub was just updated to v1.2.0 which fixes the issue
