### ISSUE TITLE
Control over the capped collection

### ISSUE THREAD

**Issue by MahmoudEzzatAbdul-Rahman** [modit/socket.io-adapter-mongo#14]
Is there any means to have control over the capped collection in the mongo db created by the module, i.e the maximum number of sockets/ records, also, if they get deleted after the socket disconnects?

**Comment by shannon** [comment]
Closing this out, please forgive the boiler plate copy-pasta:
This project has a new maintainer: [lklepner/socket.io-adapter-mongo](https://github.com/lklepner/socket.io-adapter-mongo). Please direct all issues and pull requests there.
