### ISSUE TITLE
this.adapter.addAll

### ISSUE THREAD

**Issue by CrackerakiUA** [modit/socket.io-adapter-mongo#15]
error show only below, but when i hide io.adapter, everything works smooth. Should i refer this issue on socket.io repo?
```
\node_modules\socket.io\lib\socket.js:244
  this.adapter.addAll(this.id, rooms, function(err){
               ^

TypeError: this.adapter.addAll is not a function
    at Socket.join (\node_modules\socket.io\lib\socket.js:244:16)
    at Socket.onconnect (\node_modules\socket.io\lib\socket.js:299:8)
    at \node_modules\socket.io\lib\namespace.js:171:16
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by lklepner** [comment]
looks like a socket.io issue

**Comment by shannon** [comment]
Closing this out, please forgive the boiler plate copy-pasta:
This project has a new maintainer: [lklepner/socket.io-adapter-mongo](https://github.com/lklepner/socket.io-adapter-mongo). Please direct all issues and pull requests there.

**Comment by CrackerakiUA** [comment]
that repo don't even have issues opened :)

**Comment by shannon** [comment]
@CrackerakiUA oh whoops :-) I guess I should have checked before I posted that.

@lklepner Can you open up issues on your repo?

**Comment by lklepner** [comment]
@CrackerakiUA @shannon oh sorry about that - issues should be open now
