### ISSUE TITLE
NOT GETTING THE OTHER CLIENTS ID

### ISSUE THREAD

**Issue by pankaj884** [modit/socket.io-adapter-mongo#16]
I am using node.js with multiple cores, but if the users connected on different cores. I am not getting their clientID. But the same thing work fine in redis.

**Comment by shannon** [comment]
Closing this out, please forgive the boiler plate copy-pasta:
This project has a new maintainer: [lklepner/socket.io-adapter-mongo](https://github.com/lklepner/socket.io-adapter-mongo). Please direct all issues and pull requests there.
