### ISSUE TITLE
No way to cleanup old broadcasts?

### ISSUE THREAD

**Issue by Monix** [modit/socket.io-adapter-mongo#4]
Module seems to work great, but I can't see any built-in support for clearing out old broadcast data thats going to accumulate in MongoDB. One possible solution would be to add an extra created_at field to the socket.io document, and then use MongoDB's TTL feature to handle cleanup.

**Comment by Monix** [comment]
Looked into the internal usage of mubsub and realised this is infact taken care of by the virtue of the Mongo store being a capped collection.

**Comment by shannonmpoole** [comment]
:) no worries. I can see why you would be concerned. Glad it's taken care of.
