### ISSUE TITLE
MubSub update

### ISSUE THREAD

**Issue by exilonX** [modit/socket.io-adapter-mongo#8]
I have used the lastest version of socket.io-adapter-mongo with mongodb 3.0.6 and I got a nasty error while connecting to mongo. I figured out it was from the mubsub mongodb driver because the mubsub version currently used 1.0.4 doesn't support mongodb 3.0.6 so I update mubsub to 1.1.2 and it worked fine. 

It would be great if you could update the package.json file with the latest version of mubsub. 

These are my dependencies with the updated mubsub:

  "dependencies": {
    "debug": "0.7.4",
    "mongodb-uri": "^0.9.7",
    "msgpack-js": "0.3.0",
    "mubsub": "^1.1.2",
    "socket.io-adapter": "0.3.0",
    "uid2": "0.0.3"
  }

**Comment by shannonmpoole** [comment]
Fixed in 0.1.5
